# Generated by Django 5.1 on 2024-11-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=4)),
                ('user_id', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('birth_date', models.DateField(default='2000-01-01')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
