# Generated by Django 5.1 on 2024-12-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
